/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EditRouteImport } from './routes/edit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditIndexRouteImport } from './routes/edit.index'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as EditProfileRouteImport } from './routes/edit.profile'
import { Route as EditNewRouteImport } from './routes/edit.new'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EditRoute = EditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditIndexRoute = EditIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EditRoute,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EditProfileRoute = EditProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => EditRoute,
} as any)
const EditNewRoute = EditNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => EditRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/edit': typeof EditRouteWithChildren
  '/login': typeof LoginRoute
  '/edit/new': typeof EditNewRoute
  '/edit/profile': typeof EditProfileRoute
  '/s/$slug': typeof SSlugRoute
  '/edit/': typeof EditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/edit/new': typeof EditNewRoute
  '/edit/profile': typeof EditProfileRoute
  '/s/$slug': typeof SSlugRoute
  '/edit': typeof EditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/edit': typeof EditRouteWithChildren
  '/login': typeof LoginRoute
  '/edit/new': typeof EditNewRoute
  '/edit/profile': typeof EditProfileRoute
  '/s/$slug': typeof SSlugRoute
  '/edit/': typeof EditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/edit'
    | '/login'
    | '/edit/new'
    | '/edit/profile'
    | '/s/$slug'
    | '/edit/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/edit/new' | '/edit/profile' | '/s/$slug' | '/edit'
  id:
    | '__root__'
    | '/'
    | '/edit'
    | '/login'
    | '/edit/new'
    | '/edit/profile'
    | '/s/$slug'
    | '/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditRoute: typeof EditRouteWithChildren
  LoginRoute: typeof LoginRoute
  SSlugRoute: typeof SSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit': {
      id: '/edit'
      path: '/edit'
      fullPath: '/edit'
      preLoaderRoute: typeof EditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/': {
      id: '/edit/'
      path: '/'
      fullPath: '/edit/'
      preLoaderRoute: typeof EditIndexRouteImport
      parentRoute: typeof EditRoute
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/profile': {
      id: '/edit/profile'
      path: '/profile'
      fullPath: '/edit/profile'
      preLoaderRoute: typeof EditProfileRouteImport
      parentRoute: typeof EditRoute
    }
    '/edit/new': {
      id: '/edit/new'
      path: '/new'
      fullPath: '/edit/new'
      preLoaderRoute: typeof EditNewRouteImport
      parentRoute: typeof EditRoute
    }
  }
}

interface EditRouteChildren {
  EditNewRoute: typeof EditNewRoute
  EditProfileRoute: typeof EditProfileRoute
  EditIndexRoute: typeof EditIndexRoute
}

const EditRouteChildren: EditRouteChildren = {
  EditNewRoute: EditNewRoute,
  EditProfileRoute: EditProfileRoute,
  EditIndexRoute: EditIndexRoute,
}

const EditRouteWithChildren = EditRoute._addFileChildren(EditRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditRoute: EditRouteWithChildren,
  LoginRoute: LoginRoute,
  SSlugRoute: SSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
